settings_header = Settings
settings_header_general = General
settings_header_video = Video
settings_header_audio = Audio
settings_header_clock = Clock
settings_audio_volume = Audio Volume
settings_monitor = Monitor
settings_audio_source = Source For Audio
settings_enum_audio_source_none = None
settings_enum_audio_source_video = Video
settings_enum_audio_source_music = Music
settings_play_state = When To Play
settings_enum_play_state_never = Never
settings_enum_play_state_desktop = Desktop
settings_enum_play_state_fullscreen = FullScreen
settings_enum_play_state_always = Always
settings_game_trans = Time Between Game Transitions in Seconds
settings_svr_interval = Time for ScreenSaver to Appear in Seconds
settings_video_corner = Video Corner Radius
settings_clock_corner = Clock Corner Radius
settings_clock_font = Clock Font
settings_clock_font_size = Clock Font Size
settings_clock_sub_font_size = Clock Sub-Font Size
settings_bckgrd_skip = Skip Games Missing a Background
settings_video_skip = Skip Games Missing Video
settings_music_skip = Skip Games Missing Music
settings_logo_skip = Skip Games Missing Logos
settings_play_backup = Play backup audio if selected is missing
settings_use_micro = Use Micro Trailer
settings_video_backup = Play backup video if selected is missing
settings_disable_while_play = Disable ScreenSaver while Playing
settings_pause_on_deac = Disable ScreenSaver When Not In Use
settings_display_clock = Display Clock
settings_display_video = Display Video
settings_display_logo = Display Logo
settings_dynamic_sort = Retrieve Dynmaic Groups in Order
settings_dynamic_sort_tip = Enabling has the downside of briefly altering the main view UI
settings_monitor_primary_indicator = (Primary)
menu_groups = Groups
menu_preview = Preview
menu_view = View
menu_delete = Delete
menu_prompt_sort = Please select a field to sort by:
menu_prompt_asc = Should the group be sorted in ascending order?
main_menu_sort = Change Sorting Field
main_menu_asc = ASC
main_menu_desc = DESC
main_menu_toggle = Toggle Active Group Status
main_menu_rename = Rename
main_menu_start = Start ScreenSaver
main_menu_dynamic = Create Dynamic Group
main_menu_load_filter = Load Filter
main_menu_set_filter = Set Filter To Active
main_menu_view_filter = View Filter
main_menu_group_name = Please enter a name for this group:
main_menu_group_name_shame = Please enter a non-empty name for this group:
main_menu_group_name_conflict = A group of the same name already exists.
main_menu_prompt_delete = Are you sure you want to delete group '{ $arg0 }'? This action cannot be undone.
main_menu_group_remove_empty = This group will have no games after this removal. Would you like to delete the group?\nOtherwise, the group will be labelled as inactive.
main_menu_selected_games = Selected Games
game_menu_preview = Preview ScreenSaver
game_menu_preview_error = Only one game can be previewed at a time.
game_menu_prompt_active = Should this be the new active group?
game_menu_add_selected = Add Selected
game_menu_remove_selected = Remove Selected
game_menu_create_selected = Create Group From Selected
game_menu_games = Games
group_save_fail = Failed to save the update to the groups due to the following error: { $arg0 }
group_sort_rnd = Random
