settings_header = Ajustes
settings_header_general = General
settings_header_video = Video
settings_header_audio = Sonido
settings_header_clock = Reloj
settings_audio_volume = Volumen del audio
settings_monitor = Pantalla:
settings_audio_source = Fuente para el audio
settings_enum_audio_source_none = Ninguno
settings_enum_audio_source_video = Video
settings_enum_audio_source_music = Música
settings_play_state = Cuando reproducirlo
settings_enum_play_state_never = Nunca
settings_enum_play_state_desktop = Escritorio
settings_enum_play_state_fullscreen = Pantalla completa
settings_enum_play_state_always = Siempre
settings_game_trans = Tiempo entre la transición entre juegos en segundos:
settings_svr_interval = Tiempo para que se active el salvapantallas en segundos:
settings_video_corner = Radio de la esquina del video:
settings_clock_corner = Radio de la esquina del reloj:
settings_clock_font = Fuente del reloj
settings_clock_font_size = Tamaño de la fuente del reloj
settings_clock_sub_font_size = Tamaño de la fuente secundaria del reloj
settings_bckgrd_skip = Ignorar juegos a los que les falta un fondo
settings_video_skip = Ignorar juegos a los que les falta el video
settings_music_skip = Ignorar los juegos a los que les falta música
settings_logo_skip = Ignorar los juegos a los que les falta el logo
settings_play_backup = Reproducir audio de reserva si el elegido no existe
settings_use_micro = Usar micro tráiler
settings_video_backup = Reproducir el video de reserva si el seleccionado no existe
settings_disable_while_play = Desactivar el salvapantallas mientras juegas
settings_pause_on_deac = Desactivar el salvapantallas cuando no esté en uso
settings_display_clock = Mostrar reloj
settings_display_video = Mostrar vídeo
settings_display_logo = Mostrar Logo
settings_monitor_primary_indicator = (Principal)
menu_groups = Grupos
menu_preview = Previsualizar
menu_delete = Borrar
menu_prompt_sort = Por favor, seleccione un campo para ordenar:
menu_prompt_asc = ¿Debe ordenarse el grupo en orden ascendente?
main_menu_sort = Cambiar campo de ordenación
main_menu_asc = ASC
main_menu_desc = DESC
main_menu_toggle = Cambiar el estado del grupo activo
main_menu_rename = Renombrar
main_menu_start = Iniciar salvapantallas
main_menu_dynamic = Crear grupo dinámico
main_menu_load_filter = Cargar filtro
main_menu_set_filter = Establecer filtro como activo
main_menu_view_filter = Ver filtro
main_menu_group_name = Por favor, introduce un nombre para este grupo:
main_menu_group_name_shame = Por favor, introduce un nombre que no esté vacío para este grupo:
main_menu_group_name_conflict = Ya existe un grupo con ese nombre.
main_menu_prompt_delete = ¿Estás seguro que quieres eliminar el grupo '{ $arg0 }'? Esta acción no se puede deshacer.
main_menu_group_remove_empty = Este grupo no tendrá juegos después de esta eliminación. ¿Quieres eliminar el grupo?\nDe lo contrario, el grupo será etiquetado como inactivo.
game_menu_preview = Previsualizar salvapantallas
game_menu_preview_error = Solo se puede previsualizar un juego a la vez.
game_menu_prompt_active = ¿Debe ser este el nuevo grupo activo?
game_menu_add_selected = Añadir seleccionados
game_menu_remove_selected = Borrar seleccionados
game_menu_create_selected = Crear un grupo a partir de los seleccionados
game_menu_games = Juegos
group_save_fail = Error al guardar la actualización de los grupos debido al siguiente error: { $arg0 }
group_sort_rnd = Aleatorio
